conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  osx_arm64: osx_64
test_on_native_only: true
azure:
  upload_packages: false
  settings_win:
    variables:
      SET_PAGEFILE: "True"
provider:
  win: azure
